title : COVID-VR
author: Noemi Maritza Lapa Romero 
# logo: 'qe-logo-large.png'

# Short description about the book
description: >-
  Brief description and results obtained in binary and ternary classification for COVID-19 tasks.

execute:
  execute_notebooks           : cache

# HTML-specific settings
html:
  home_page_in_navbar         : false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://github.com/covid-vr/jb-covid-vr
  path_to_book                : "mini_book"

# binder:
#   binderhub_url               : "https://mybinder.org"
#   text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    - html_image
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist
